### ISSUE TITLE
BUG: message view doesn't display images posted using planetary ios app.

### ISSUE THREAD

**Issue by rabble** [planetary-social/viewer#21]
Right now we don't display images if they're posted using the plaentary ios app. 

![Screen Shot 2022-02-24 at 6 58 22 AM](https://user-images.githubusercontent.com/76/155379009-743048ee-6987-48ac-91b6-61da6dbd85df.png)
![Screen Shot 2022-02-24 at 7 01 11 AM](https://user-images.githubusercontent.com/76/155379298-4b5834a0-30d3-4e3f-b4e1-b4787c64fe74.png)
https://planetary.link/msg/%25LIij36fFI2Ymoh98Nh%2B1Pd8ebzcert2ZB%2F8zco%2Be9Tk%3D.sha256

Also as you can see from the screenshot the planetary.link version has a lot less posts than my patchwork.

**Comment by setch-l** [comment]
Fixed.
